"""Drift test: Pydantic models ↔ pyarrow schemas ↔ BQ JSON schemas.

Each pipeline table has up to three schema representations:
  - Pydantic: the domain model validated at ingest time
  - Arrow: the explicit pa.Schema that writes typed Parquet files
  - BQ JSON: the Terraform-managed schema that pre-provisions the BQ table

All three must stay in sync. Drift between any two causes:
  - Pydantic↔Arrow drift: fields silently dropped when writing Parquet
    (dataframe_to_table projects only Arrow fields — no error, no warning)
  - Arrow↔BQ JSON drift: BQ rejects Parquet on load with
    "Provided Schema does not match Table" (BL-11 incident, 2026-04-19)

Three assertions per triple (skipped when a leg is absent by design):
  1. Arrow ↔ BQ JSON — name-based, order-sensitive.
  2. Pydantic ↔ Arrow — field name set equality + Optional→nullable.
  3. Pydantic ↔ BQ JSON — field name set equality + Optional→NULLABLE.

G-02 gap: silver_social_posts and raw_social_posts_dlq have no dedicated
Pydantic model (transformation is inline, from SocialPost raw). Assertions 2
and 3 are skipped for those triples; Arrow↔BQ JSON (assertion 1) still runs.

Why order matters in assertion 1 even though BQ Parquet loading is name-based:
  - Reordering changes the physical column layout in Parquet, which can break
    tools that read files outside BQ (DuckDB dev, audit scripts, notebooks).
  - Enforcing order guards against auto-formatters silently scrambling the
    intentional grouping conventions (lineage fields last, entity fields grouped).
"""

from __future__ import annotations

import json
import types
import typing
from dataclasses import dataclass
from pathlib import Path

import pyarrow as pa
import pytest
from mapear_domain.models.base import GoldArticle, RawArticle, SilverArticle
from mapear_social.parquet_schemas import (
    SOCIAL_DLQ_SCHEMA,
    SOCIAL_RAW_SCHEMA,
    SOCIAL_SILVER_SCHEMA,
)
from pydantic import BaseModel

from mapear_storage.loaders.parquet_writer import (
    GOLD_ARTICLE_SCHEMA,
    RAW_ARTICLE_SCHEMA,
    SILVER_ARTICLE_SCHEMA,
)

try:
    from mapear_social.models import (
        SilverSocialPost as _SilverSocialPost,
    )
    from mapear_social.models import (
        SocialPost as _SocialPost,
    )
    from mapear_social.models import (
        SocialPostDLQ as _SocialPostDLQ,
    )

    _SOCIAL_POST: type[BaseModel] | None = _SocialPost
    _SILVER_SOCIAL_POST: type[BaseModel] | None = _SilverSocialPost
    _SOCIAL_POST_DLQ: type[BaseModel] | None = _SocialPostDLQ
except ImportError:
    # mapear-social not installed — SocialPost Pydantic assertions skipped.
    # Full coverage requires: poetry run pip install -e ../mapear-social --no-deps
    _SOCIAL_POST = None
    _SILVER_SOCIAL_POST = None
    _SOCIAL_POST_DLQ = None


def _schemas_dir() -> Path:
    """Locate infra/modules/bigquery/schemas by walking up from this file —
    stable regardless of how deep the package sits in the monorepo."""
    for parent in Path(__file__).resolve().parents:
        candidate = parent / "infra" / "modules" / "bigquery" / "schemas"
        if candidate.is_dir():
            return candidate
    raise RuntimeError("BigQuery schemas directory not found")


SCHEMAS_DIR = _schemas_dir()


# --- SchemaTriple ------------------------------------------------------------


@dataclass
class SchemaTriple:
    """One pipeline table with up to three schema representations."""

    table: str
    arrow: pa.Schema
    bq_json: Path
    pydantic: type[BaseModel] | None = None


SCHEMA_TRIPLES: list[SchemaTriple] = [
    # Triplas completas: Pydantic + Arrow + BQ JSON
    SchemaTriple(
        table="raw_articles",
        pydantic=RawArticle,
        arrow=RAW_ARTICLE_SCHEMA,
        bq_json=SCHEMAS_DIR / "raw_articles.json",
    ),
    SchemaTriple(
        table="silver_articles",
        pydantic=SilverArticle,
        arrow=SILVER_ARTICLE_SCHEMA,
        bq_json=SCHEMAS_DIR / "silver_articles.json",
    ),
    SchemaTriple(
        table="gold_articles",
        pydantic=GoldArticle,
        arrow=GOLD_ARTICLE_SCHEMA,
        bq_json=SCHEMAS_DIR / "gold_articles.json",
    ),
    SchemaTriple(
        table="raw_social_posts",
        pydantic=_SOCIAL_POST,  # None when mapear-social not installed
        arrow=SOCIAL_RAW_SCHEMA,
        bq_json=SCHEMAS_DIR / "raw_social_posts.json",
    ),
    # G-02 closed in Stage 1B (2026-05-10): silver_social_posts and DLQ now
    # have dedicated Pydantic models, generated by mapear-social/contracts.py.
    SchemaTriple(
        table="silver_social_posts",
        pydantic=_SILVER_SOCIAL_POST,
        arrow=SOCIAL_SILVER_SCHEMA,
        bq_json=SCHEMAS_DIR / "silver_social_posts.json",
    ),
    SchemaTriple(
        table="raw_social_posts_dlq",
        pydantic=_SOCIAL_POST_DLQ,
        arrow=SOCIAL_DLQ_SCHEMA,
        bq_json=SCHEMAS_DIR / "raw_social_posts_dlq.json",
    ),
]


# --- Arrow → BQ JSON conversion helpers -------------------------------------


def _pa_type_to_bq(t: pa.DataType) -> str:
    if pa.types.is_string(t):
        return "STRING"
    if pa.types.is_int64(t):
        return "INT64"
    if pa.types.is_float64(t):
        return "FLOAT64"
    if pa.types.is_boolean(t):
        return "BOOL"
    if pa.types.is_timestamp(t):
        return "TIMESTAMP"
    raise AssertionError(f"unmapped pyarrow scalar type: {t}")


def _pa_field_to_bq(field: pa.Field) -> dict:
    t = field.type

    if pa.types.is_list(t):
        value_type = t.value_type
        if pa.types.is_struct(value_type):
            return {
                "name": field.name,
                "type": "RECORD",
                "mode": "REPEATED",
                "fields": [
                    _pa_field_to_bq(value_type.field(i))
                    for i in range(value_type.num_fields)
                ],
            }
        return {
            "name": field.name,
            "type": _pa_type_to_bq(value_type),
            "mode": "REPEATED",
        }

    mode = "NULLABLE" if field.nullable else "REQUIRED"

    if pa.types.is_struct(t):
        return {
            "name": field.name,
            "type": "RECORD",
            "mode": mode,
            "fields": [_pa_field_to_bq(t.field(i)) for i in range(t.num_fields)],
        }

    return {"name": field.name, "type": _pa_type_to_bq(t), "mode": mode}


def _pa_schema_to_bq_json(schema: pa.Schema) -> list[dict]:
    return [_pa_field_to_bq(schema.field(i)) for i in range(len(schema))]


# --- Pydantic introspection helpers -----------------------------------------


def _is_optional(annotation: object) -> bool:
    """True iff annotation is X | None (handles both typing.Union and PEP 604 |)."""
    origin = typing.get_origin(annotation)
    if origin is typing.Union:
        return type(None) in typing.get_args(annotation)
    if isinstance(annotation, types.UnionType):
        return type(None) in typing.get_args(annotation)
    return False


def _pydantic_field_names(model: type[BaseModel]) -> set[str]:
    """All field names: regular model_fields plus @computed_field properties."""
    return set(model.model_fields) | set(model.model_computed_fields)


def _pydantic_annotation(model: type[BaseModel], name: str) -> object:
    if name in model.model_fields:
        return model.model_fields[name].annotation
    cf = model.model_computed_fields.get(name)
    return cf.return_type if cf else None


# --- Tests ------------------------------------------------------------------


@pytest.mark.parametrize("triple", SCHEMA_TRIPLES, ids=lambda t: t.table)
def test_arrow_bq_json_drift(triple: SchemaTriple) -> None:
    """Arrow ↔ BQ JSON: schemas must match exactly, including field order."""
    json_path = triple.bq_json
    assert json_path.exists(), (
        f"BQ schema file missing: {json_path}\n"
        f"  Tabela `{triple.table}` não é Terraform-managed. "
        "Adicionar o JSON e um google_bigquery_table em main.tf.\n"
        "  Ver SCHEMAS.md §4.3."
    )
    on_disk = json.loads(json_path.read_text())
    derived = _pa_schema_to_bq_json(triple.arrow)
    assert derived == on_disk, (
        f"Drift Arrow↔BQ JSON em `{triple.table}`.\n"
        "  Atualizar ambos no mesmo commit para que as tabelas Terraform aceitem "
        "o Parquet carregado pelo pipeline (lição BL-11)."
    )


@pytest.mark.parametrize("triple", SCHEMA_TRIPLES, ids=lambda t: t.table)
def test_pydantic_arrow_field_names(triple: SchemaTriple) -> None:
    """Pydantic ↔ Arrow: field names must match (set equality) + Optional→nullable.

    If a Pydantic field is absent from the Arrow schema, dataframe_to_table drops
    it silently — no error, no warning. This is how D-01 (actor_run_id,
    ingestion_run_id absent from RAW_ARTICLE_SCHEMA) was undetected until B3.

    Nullability rule (unidirectional): Optional[X] in Pydantic → nullable=True in
    Arrow. The converse (nullable Arrow with non-Optional Pydantic) is permissible
    — BQLoader is fail-loud on missing fields, not on null values.

    Limitation — type compatibility is NOT validated here (only field names and
    nullability). A field with Pydantic type `int` mapped to Arrow `pa.string()`
    would pass this test but fail at write time with a pyarrow cast error. Type
    compat is indirectly covered by the Arrow↔BQ JSON ladder: Arrow and BQ JSON
    must agree on type, and BQLoader enforces the BQ type at load time. Direct
    Pydantic→Arrow type checking is tracked as tech debt in
    docs/tech_debt_drift_test_type_coverage.md.
    """
    if triple.pydantic is None:
        pytest.skip(
            f"Sem modelo Pydantic para `{triple.table}` "
            "(G-02: ETL inline sem modelo dedicado)"
        )

    pydantic_names = _pydantic_field_names(triple.pydantic)
    arrow_names = {triple.arrow.field(i).name for i in range(len(triple.arrow))}

    diffs: list[str] = []
    for name in sorted(pydantic_names - arrow_names):
        ann = _pydantic_annotation(triple.pydantic, name)
        diffs.append(
            f"  `{name}` ({ann!r}): presente em Pydantic, AUSENTE em Arrow "
            "→ campo silenciosamente descartado no Parquet"
        )
    for name in sorted(arrow_names - pydantic_names):
        diffs.append(f"  `{name}`: presente em Arrow, AUSENTE em Pydantic")

    if diffs:
        raise AssertionError(
            f"Drift de campo Pydantic↔Arrow em `{triple.table}`:\n"
            + "\n".join(diffs)
            + "\n  Ação: alinhar as duas pontas no mesmo commit."
            + " Ver SCHEMAS.md §4.3 e §6."
        )

    arrow_by_name = {
        triple.arrow.field(i).name: triple.arrow.field(i)
        for i in range(len(triple.arrow))
    }
    null_diffs: list[str] = []
    for name in pydantic_names:
        ann = _pydantic_annotation(triple.pydantic, name)
        if _is_optional(ann) and not arrow_by_name[name].nullable:
            null_diffs.append(
                f"  `{name}` ({ann!r}): Pydantic Optional mas Arrow nullable=False "
                "→ pipeline tentará escrever None num campo REQUIRED"
            )
    if null_diffs:
        raise AssertionError(
            f"Drift de nullabilidade Pydantic↔Arrow em `{triple.table}`:\n"
            + "\n".join(null_diffs)
            + "\n  Ação: marcar o campo Arrow como nullable=True. Ver SCHEMAS.md §4.3."
        )


@pytest.mark.parametrize("triple", SCHEMA_TRIPLES, ids=lambda t: t.table)
def test_pydantic_bq_field_names(triple: SchemaTriple) -> None:
    """Pydantic ↔ BQ JSON: field names must match (set equality) + Optional→NULLABLE.

    mode=NULLABLE is BQ's permissive default; a non-Optional Pydantic field mapped
    to NULLABLE is acceptable (BQLoader is fail-loud on absent fields, not on null).
    """
    if triple.pydantic is None:
        pytest.skip(
            f"Sem modelo Pydantic para `{triple.table}` "
            "(G-02: ETL inline sem modelo dedicado)"
        )

    json_path = triple.bq_json
    if not json_path.exists():
        pytest.fail(
            f"BQ schema file missing: {json_path}\n"
            f"  Não é possível validar Pydantic↔BQ para `{triple.table}` sem o JSON.\n"
            "  Formalizar a tabela no Terraform primeiro (SCHEMAS.md §4.3)."
        )

    bq_schema = json.loads(json_path.read_text())
    bq_by_name = {f["name"]: f for f in bq_schema}
    pydantic_names = _pydantic_field_names(triple.pydantic)
    bq_names = set(bq_by_name)

    diffs: list[str] = []
    for name in sorted(pydantic_names - bq_names):
        ann = _pydantic_annotation(triple.pydantic, name)
        diffs.append(f"  `{name}` ({ann!r}): presente em Pydantic, AUSENTE em BQ JSON")
    for name in sorted(bq_names - pydantic_names):
        diffs.append(f"  `{name}`: presente em BQ JSON, AUSENTE em Pydantic")

    if diffs:
        raise AssertionError(
            f"Drift de campo Pydantic↔BQ JSON em `{triple.table}`:\n"
            + "\n".join(diffs)
            + "\n  Ação: alinhar as duas pontas no mesmo commit. Ver SCHEMAS.md §4.3."
        )

    null_diffs: list[str] = []
    for name in pydantic_names:
        ann = _pydantic_annotation(triple.pydantic, name)
        mode = bq_by_name[name].get("mode", "NULLABLE")
        if _is_optional(ann) and mode == "REQUIRED":
            null_diffs.append(
                f"  `{name}` ({ann!r}): Pydantic Optional mas BQ mode=REQUIRED "
                "→ INSERT com NULL rejeitado pelo BQ"
            )
    if null_diffs:
        raise AssertionError(
            f"Drift de nullabilidade Pydantic↔BQ JSON em `{triple.table}`:\n"
            + "\n".join(null_diffs)
            + "\n  Ação: mudar para mode=NULLABLE. Ver SCHEMAS.md §4.3."
        )
